const pageModules = import.meta.glob([
  "../tools/*/index.html",
  "!../tools/_*/index.html",
]);

const preferredOrder = [
  "json-formatter",
  "timestamp-converter",
  "codec",
  "string-generator",
  "hosts-manager",
  "url-lab",
  "regex-lab",
  "text-diff",
  "data-format",
  "number-base",
  "cron-expression",
  "ip-cidr",
  "ip-inspector",
  "color-lab",
  "image-process",
  "xml-plist",
  "qr-code",
  "jwt-lab",
  "chmod-lab",
  "cert-lab",
  "text-lab",
  "curl-lab",
  "connection-trace",
];

/** Localized title/description for known tools; unknown folders still appear by id. */
export const toolMeta = {
  "hosts-manager": {
    title: {
      en: "Hosts Manager",
      "zh-Hans": "Hosts 管理",
      "zh-Hant": "Hosts 管理",
      ja: "Hosts 管理",
      ko: "Hosts 관리",
      es: "Gestor de hosts",
      fr: "Gestionnaire Hosts",
      de: "Hosts-Manager",
      "pt-BR": "Gerenciador de hosts",
      ru: "Менеджер hosts",
    },
    description: {
      en: "View the system hosts file and switch mappings between environments",
      "zh-Hans": "查看系统 hosts，并在开发环境间切换映射",
      "zh-Hant": "檢視系統 hosts，並在開發環境間切換對應",
      ja: "システム hosts を確認し、環境ごとにマッピングを切り替え",
      ko: "시스템 hosts를 확인하고 환경별 매핑을 전환",
      es: "Consulta /etc/hosts y cambia mapeos entre entornos",
      fr: "Consultez /etc/hosts et basculez les mappings par environnement",
      de: "System-Hosts ansehen und Umgebungs-Mappings wechseln",
      "pt-BR": "Veja o hosts do sistema e alterne mapeamentos entre ambientes",
      ru: "Просмотр /etc/hosts и переключение окружений",
    },
  },
  "timestamp-converter": {
    title: {
      en: "Timestamp Converter",
      "zh-Hans": "时间戳转换",
      "zh-Hant": "時間戳轉換",
      ja: "タイムスタンプ変換",
      ko: "타임스탬프 변환",
      es: "Conversor de marcas de tiempo",
      fr: "Convertisseur d’horodatage",
      de: "Zeitstempel-Konverter",
      "pt-BR": "Conversor de timestamp",
      ru: "Конвертер временных меток",
    },
    description: {
      en: "Convert dates and Unix timestamps across units and time zones",
      "zh-Hans": "在不同单位和时区之间转换日期与 Unix 时间戳",
      "zh-Hant": "在不同單位和時區之間轉換日期與 Unix 時間戳",
      ja: "日付と Unix タイムスタンプを単位・タイムゾーン間で変換",
      ko: "날짜와 Unix 타임스탬프를 단위 및 시간대별로 변환",
      es: "Convierte fechas y marcas Unix entre unidades y zonas",
      fr: "Convertissez dates et horodatages Unix entre unités et fuseaux",
      de: "Datum und Unix-Zeitstempel zwischen Einheiten und Zeitzonen",
      "pt-BR": "Converta datas e timestamps Unix entre unidades e fusos",
      ru: "Преобразование дат и меток Unix между единицами и поясами",
    },
  },
  "json-formatter": {
    title: {
      en: "JSON Formatter",
      "zh-Hans": "JSON 格式化",
      "zh-Hant": "JSON 格式化",
      ja: "JSON フォーマッタ",
      ko: "JSON 포맷터",
      es: "Formateador JSON",
      fr: "Formateur JSON",
      de: "JSON-Formatierer",
      "pt-BR": "Formatador JSON",
      ru: "Форматирование JSON",
    },
    description: {
      en: "Format, minify, and query JSON with path expressions",
      "zh-Hans": "格式化、压缩，并用路径表达式查询 JSON",
      "zh-Hant": "格式化、壓縮，並用路徑運算式查詢 JSON",
      ja: "JSON の整形・圧縮・パス式クエリ",
      ko: "JSON 포맷·압축 및 경로 표현식 조회",
      es: "Formatea, minifica y consulta JSON con rutas",
      fr: "Formatez, minifiez et interrogez du JSON par chemin",
      de: "JSON formatieren, verkleinern und per Pfad abfragen",
      "pt-BR": "Formate, minifique e consulte JSON com caminhos",
      ru: "Форматирование, сжатие и запросы JSON по путям",
    },
  },
  codec: {
    title: {
      en: "Codec",
      "zh-Hans": "编解码",
      "zh-Hant": "編解碼",
      ja: "コーデック",
      ko: "코덱",
      es: "Códec",
      fr: "Codec",
      de: "Codec",
      "pt-BR": "Codec",
      ru: "Кодек",
    },
    description: {
      en: "Encode and decode Base64, Hex, URL, HTML, Unicode, Escape, and Hash",
      "zh-Hans": "编解码 Base64、Hex、URL、HTML、Unicode、转义与哈希",
      "zh-Hant": "編解碼 Base64、Hex、URL、HTML、Unicode、跳脫與雜湊",
      ja: "Base64・Hex・URL・HTML・Unicode・エスケープ・ハッシュ",
      ko: "Base64, Hex, URL, HTML, Unicode, 이스케이프, 해시",
      es: "Codifica y decodifica Base64, Hex, URL, HTML, Unicode y hash",
      fr: "Encodez et décodez Base64, Hex, URL, HTML, Unicode et hash",
      de: "Kodieren und dekodieren: Base64, Hex, URL, HTML, Unicode, Hash",
      "pt-BR": "Codifique e decodifique Base64, Hex, URL, HTML, Unicode e hash",
      ru: "Кодирование Base64, Hex, URL, HTML, Unicode, escape и хеш",
    },
  },
  "string-generator": {
    title: {
      en: "String Generator",
      "zh-Hans": "字符串生成",
      "zh-Hant": "字串產生",
      ja: "文字列ジェネレーター",
      ko: "문자열 생성기",
      es: "Generador de cadenas",
      fr: "Générateur de chaînes",
      de: "String-Generator",
      "pt-BR": "Gerador de strings",
      ru: "Генератор строк",
    },
    description: {
      en: "Generate UUIDs, random IDs, and passwords locally",
      "zh-Hans": "本地生成 UUID、随机 ID 与密码",
      "zh-Hant": "本機產生 UUID、隨機 ID 與密碼",
      ja: "UUID・ランダム ID・パスワードをローカル生成",
      ko: "UUID, 임의 ID, 비밀번호를 로컬에서 생성",
      es: "Genera UUID, ID aleatorios y contraseñas en local",
      fr: "Générez UUID, ID aléatoires et mots de passe localement",
      de: "UUIDs, Zufalls-IDs und Passwörter lokal erzeugen",
      "pt-BR": "Gere UUIDs, IDs aleatórios e senhas localmente",
      ru: "Локально создавайте UUID, случайные ID и пароли",
    },
  },
  "regex-lab": {
    title: {
      en: "Regex Lab",
      "zh-Hans": "正则实验室",
      "zh-Hant": "正則實驗室",
      ja: "正規表現ラボ",
      ko: "정규식 랩",
      es: "Laboratorio regex",
      fr: "Labo regex",
      de: "Regex-Labor",
      "pt-BR": "Lab de regex",
      ru: "Лаборатория regex",
    },
    description: {
      en: "Highlight matches, inspect capture groups, and try common replacements",
      "zh-Hans": "匹配高亮、分组捕获与常用替换",
      "zh-Hant": "符合高亮、分組擷取與常用取代",
      ja: "一致強調・キャプチャ・よく使う置換",
      ko: "일치 강조, 캡처 그룹, 자주 쓰는 치환",
      es: "Resalta coincidencias, grupos y sustituciones habituales",
      fr: "Surlignage, groupes de capture et remplacements courants",
      de: "Treffer hervorheben, Gruppen prüfen, Ersetzungen testen",
      "pt-BR": "Destaque matches, grupos e substituições comuns",
      ru: "Подсветка совпадений, группы и типичные замены",
    },
  },
  "text-diff": {
    title: {
      en: "Text Diff",
      "zh-Hans": "文本 Diff",
      "zh-Hant": "文字 Diff",
      ja: "テキスト Diff",
      ko: "텍스트 Diff",
      es: "Diff de texto",
      fr: "Diff de texte",
      de: "Text-Diff",
      "pt-BR": "Diff de texto",
      ru: "Diff текста",
    },
    description: {
      en: "Compare two texts side by side with line-level highlighting",
      "zh-Hans": "左右对比文本并高亮行级差异",
      "zh-Hant": "左右比對文字並高亮行級差異",
      ja: "左右比較と行単位の差分強調",
      ko: "좌우 비교와 행 단위 강조",
      es: "Compara textos en paralelo con resaltado por líneas",
      fr: "Comparez deux textes côte à côte, ligne par ligne",
      de: "Texte nebeneinander mit zeilenweiser Hervorhebung vergleichen",
      "pt-BR": "Compare textos lado a lado com destaque por linha",
      ru: "Сравнение двух текстов с подсветкой по строкам",
    },
  },
  "ip-cidr": {
    title: {
      en: "IP / CIDR Calculator",
      "zh-Hans": "IP / CIDR 计算器",
      "zh-Hant": "IP / CIDR 計算器",
      ja: "IP / CIDR 計算機",
      ko: "IP / CIDR 계산기",
      es: "Calculadora IP / CIDR",
      fr: "Calculateur IP / CIDR",
      de: "IP-/CIDR-Rechner",
      "pt-BR": "Calculadora IP / CIDR",
      ru: "Калькулятор IP / CIDR",
    },
    description: {
      en: "Calculate IPv4 network details, ranges, and membership checks",
      "zh-Hans": "计算 IPv4 网段、范围与归属判断",
      "zh-Hant": "計算 IPv4 網段、範圍與歸屬判斷",
      ja: "IPv4 の網情報・範囲・所属判定",
      ko: "IPv4 네트워크 정보·범위·포함 여부 계산",
      es: "Calcula detalles, rangos y pertenencia IPv4",
      fr: "Calculez détails, plages et appartenance IPv4",
      de: "IPv4-Netzdetails, Bereiche und Zugehörigkeit",
      "pt-BR": "Calcule detalhes, intervalos e pertencimento IPv4",
      ru: "Расчёт IPv4: детали сети, диапазон и вхождение",
    },
  },
  "cron-expression": {
    title: {
      en: "Cron Expression",
      "zh-Hans": "Cron 表达式",
      "zh-Hant": "Cron 運算式",
      ja: "Cron 式",
      ko: "Cron 표현식",
      es: "Expresión cron",
      fr: "Expression cron",
      de: "Cron-Ausdruck",
      "pt-BR": "Expressão cron",
      ru: "Cron-выражение",
    },
    description: {
      en: "Build five-field cron schedules and preview upcoming runs",
      "zh-Hans": "编写五段 cron 并预览接下来的执行时间",
      "zh-Hant": "編寫五段 cron 並預覽接下來的執行時間",
      ja: "5 フィールド cron と次回実行の確認",
      ko: "5필드 cron 작성과 다음 실행 미리보기",
      es: "Crea cron de cinco campos y ve próximas ejecuciones",
      fr: "Créez des cron à cinq champs et voyez les prochaines exécutions",
      de: "Fünf-Feld-Cron erstellen und nächste Läufe prüfen",
      "pt-BR": "Crie cron de cinco campos e veja próximas execuções",
      ru: "Пятиполевой cron и ближайшие запуски",
    },
  },
  "data-format": {
    title: {
      en: "Data Format",
      "zh-Hans": "数据格式",
      "zh-Hant": "資料格式",
      ja: "データ形式",
      ko: "데이터 형식",
      es: "Formato de datos",
      fr: "Format de données",
      de: "Datenformat",
      "pt-BR": "Formato de dados",
      ru: "Формат данных",
    },
    description: {
      en: "Convert between JSON, YAML, and TOML locally",
      "zh-Hans": "本地转换 JSON、YAML 与 TOML",
      "zh-Hant": "本機轉換 JSON、YAML 與 TOML",
      ja: "JSON・YAML・TOML をローカル変換",
      ko: "JSON, YAML, TOML을 로컬에서 변환",
      es: "Convierte JSON, YAML y TOML en local",
      fr: "Convertissez JSON, YAML et TOML en local",
      de: "JSON, YAML und TOML lokal umwandeln",
      "pt-BR": "Converta JSON, YAML e TOML localmente",
      ru: "Локальная конвертация JSON, YAML и TOML",
    },
  },
  "color-lab": {
    title: {
      en: "Color Lab",
      "zh-Hans": "颜色实验室",
      "zh-Hant": "顏色實驗室",
      ja: "カラーラボ",
      ko: "색상 랩",
      es: "Laboratorio de color",
      fr: "Labo couleur",
      de: "Farblabor",
      "pt-BR": "Lab de cores",
      ru: "Цветовая лаборатория",
    },
    description: {
      en: "Convert HEX, RGB, HSL, and HSV with local contrast checks",
      "zh-Hans": "本地转换 HEX / RGB / HSL / HSV 并检查对比度",
      "zh-Hant": "本機轉換 HEX / RGB / HSL / HSV 並檢查對比度",
      ja: "HEX・RGB・HSL・HSV 変換とコントラスト確認",
      ko: "HEX, RGB, HSL, HSV 변환과 대비 확인",
      es: "Convierte HEX, RGB, HSL y HSV con contraste local",
      fr: "Convertissez HEX, RGB, HSL et HSV avec contraste local",
      de: "HEX, RGB, HSL und HSV lokal mit Kontrastprüfung",
      "pt-BR": "Converta HEX, RGB, HSL e HSV com contraste local",
      ru: "Конвертация HEX, RGB, HSL, HSV и проверка контраста",
    },
  },
  "qr-code": {
    title: {
      en: "QR Code",
      "zh-Hans": "二维码",
      "zh-Hant": "QR 碼",
      ja: "QR コード",
      ko: "QR 코드",
      es: "Código QR",
      fr: "Code QR",
      de: "QR-Code",
      "pt-BR": "Código QR",
      ru: "QR-код",
    },
    description: {
      en: "Generate QR codes from text or URLs locally",
      "zh-Hans": "本地从文本或 URL 生成二维码",
      "zh-Hant": "本機從文字或 URL 產生 QR 碼",
      ja: "テキストや URL から QR をローカル生成",
      ko: "텍스트나 URL로 QR을 로컬 생성",
      es: "Genera códigos QR desde texto o URL en local",
      fr: "Générez des QR à partir de texte ou d’URL en local",
      de: "QR-Codes lokal aus Text oder URLs erzeugen",
      "pt-BR": "Gere códigos QR a partir de texto ou URL localmente",
      ru: "Локально создавайте QR из текста или URL",
    },
  },
  "url-lab": {
    title: {
      en: "URL Lab",
      "zh-Hans": "URL 实验室",
      "zh-Hant": "URL 實驗室",
      ja: "URL ラボ",
      ko: "URL 랩",
      es: "Lab URL",
      fr: "Labo URL",
      de: "URL-Labor",
      "pt-BR": "Lab URL",
      ru: "URL-лаборатория",
    },
    description: {
      en: "Parse and rebuild URLs with query and hash editing",
      "zh-Hans": "解析与拼装 URL，编辑查询参数与哈希",
      "zh-Hant": "解析與組裝 URL，編輯查詢參數與雜湊",
      ja: "URL の解析・再構成とクエリ編集",
      ko: "URL 파싱·조립과 쿼리 편집",
      es: "Analiza y reconstruye URLs con query y hash",
      fr: "Analysez et reconstruisez des URL avec requête et hash",
      de: "URLs zerlegen und mit Query/Hash neu bauen",
      "pt-BR": "Analise e remonte URLs com query e hash",
      ru: "Разбор и сборка URL с query и hash",
    },
  },
  "number-base": {
    title: {
      en: "Unit Converter",
      "zh-Hans": "单位换算",
      "zh-Hant": "單位換算",
      ja: "単位変換",
      ko: "단위 변환",
      es: "Conversor de unidades",
      fr: "Convertisseur d’unités",
      de: "Einheitenrechner",
      "pt-BR": "Conversor de unidades",
      ru: "Конвертер единиц",
    },
    description: {
      en: "Convert bases, bytes, time, length, mass, temperature, and more locally",
      "zh-Hans": "本地换算进制、字节、时间、长度、质量、温度等",
      "zh-Hant": "本機換算進位、位元組、時間、長度、質量、溫度等",
      ja: "基数・バイト・時間・長さ・質量・温度などをローカル変換",
      ko: "진법, 바이트, 시간, 길이, 질량, 온도 등을 로컬 변환",
      es: "Convierte bases, bytes, tiempo, longitud, masa, temperatura y más",
      fr: "Convertissez bases, octets, temps, longueur, masse, température et plus",
      de: "Basen, Bytes, Zeit, Länge, Masse, Temperatur und mehr lokal umwandeln",
      "pt-BR": "Converta bases, bytes, tempo, comprimento, massa, temperatura e mais",
      ru: "Локальный перевод оснований, байтов, времени, длины, массы, температуры и др.",
    },
  },
  "xml-plist": {
    title: {
      en: "XML / Plist",
      "zh-Hans": "XML / Plist",
      "zh-Hant": "XML / Plist",
      ja: "XML / Plist",
      ko: "XML / Plist",
      es: "XML / Plist",
      fr: "XML / Plist",
      de: "XML / Plist",
      "pt-BR": "XML / Plist",
      ru: "XML / Plist",
    },
    description: {
      en: "Format XML and convert Apple XML plists to JSON locally",
      "zh-Hans": "本地格式化 XML，并将 XML plist 转为 JSON",
      "zh-Hant": "本機格式化 XML，並將 XML plist 轉為 JSON",
      ja: "XML 整形と XML plist の JSON 変換",
      ko: "XML 정렬과 XML plist→JSON 변환",
      es: "Formatea XML y convierte plists XML a JSON en local",
      fr: "Formatez du XML et convertissez les plists XML en JSON",
      de: "XML formatieren und XML-plists nach JSON wandeln",
      "pt-BR": "Formate XML e converta plists XML para JSON",
      ru: "Форматирование XML и конвертация XML-plist в JSON",
    },
  },
  "ip-inspector": {
    title: {
      en: "IP Inspector",
      "zh-Hans": "IP 解析",
      "zh-Hant": "IP 解析",
      ja: "IP インスペクタ",
      ko: "IP 검사기",
      es: "Inspector IP",
      fr: "Inspecteur IP",
      de: "IP-Inspektor",
      "pt-BR": "Inspetor IP",
      ru: "IP-инспектор",
    },
    description: {
      en: "Inspect IPv4 and IPv6 addresses, kinds, and reverse DNS labels",
      "zh-Hans": "查看 IPv4 / IPv6 类型、整数与反向 DNS 标签",
      "zh-Hant": "檢視 IPv4 / IPv6 類型、整數與反向 DNS 標籤",
      ja: "IPv4 / IPv6 の種別・整数・逆引きを確認",
      ko: "IPv4/IPv6 유형·정수·역방향 DNS 확인",
      es: "Inspecciona IPv4/IPv6, tipos y DNS inverso",
      fr: "Inspectez IPv4/IPv6, types et DNS inverse",
      de: "IPv4/IPv6, Typen und Reverse-DNS prüfen",
      "pt-BR": "Inspecione IPv4/IPv6, tipos e DNS reverso",
      ru: "Разбор IPv4/IPv6, типов и reverse DNS",
    },
  },
  "image-process": {
    title: {
      en: "Image Tools",
      "zh-Hans": "图片处理",
      "zh-Hant": "圖片處理",
      ja: "画像ツール",
      ko: "이미지 도구",
      es: "Herramientas de imagen",
      fr: "Outils image",
      de: "Bildwerkzeuge",
      "pt-BR": "Ferramentas de imagem",
      ru: "Инструменты изображений",
    },
    description: {
      en: "Convert formats and control output by quality, target size, or dimensions",
      "zh-Hans": "转换格式，并按质量、目标大小或尺寸控制输出",
      "zh-Hant": "轉換格式，並依品質、目標大小或尺寸控制輸出",
      ja: "形式変換と品質・目標サイズ・寸法での出力制御",
      ko: "형식 변환과 품질·목표 용량·크기 출력 제어",
      es: "Convierte formatos y controla la salida por calidad, tamaño o dimensiones",
      fr: "Convertissez les formats et contrôlez la sortie par qualité, taille ou dimensions",
      de: "Formate konvertieren und Ausgabe per Qualität, Zielgröße oder Abmessungen steuern",
      "pt-BR": "Converta formatos e controle a saída por qualidade, tamanho ou dimensões",
      ru: "Конвертация форматов и управление выводом по качеству, размеру или габаритам",
    },
  },
  "jwt-lab": {
    title: {
      en: "JWT Lab",
      "zh-Hans": "JWT 查看",
      "zh-Hant": "JWT 檢視",
      ja: "JWT ラボ",
      ko: "JWT 랩",
      es: "JWT Lab",
      fr: "JWT Lab",
      de: "JWT Lab",
      "pt-BR": "JWT Lab",
      ru: "JWT Lab",
    },
    description: {
      en: "Decode JWT headers and payloads locally without uploading tokens",
      "zh-Hans": "本地解码 JWT，不上传 Token",
      "zh-Hant": "本機解碼 JWT，不上傳 Token",
      ja: "JWT をローカルでデコード（送信なし）",
      ko: "JWT를 로컬에서 디코딩 (업로드 없음)",
      es: "Decodifica JWT en local sin subir tokens",
      fr: "Décodez les JWT en local sans les envoyer",
      de: "JWT lokal dekodieren ohne Upload",
      "pt-BR": "Decodifique JWT localmente sem enviar tokens",
      ru: "Локально декодируйте JWT без отправки",
    },
  },
  "chmod-lab": {
    title: {
      en: "chmod Lab",
      "zh-Hans": "权限换算",
      "zh-Hant": "權限換算",
      ja: "chmod ラボ",
      ko: "chmod 랩",
      es: "chmod Lab",
      fr: "chmod Lab",
      de: "chmod Lab",
      "pt-BR": "chmod Lab",
      ru: "chmod Lab",
    },
    description: {
      en: "Convert Unix file modes between octal, symbolic, and permission bits",
      "zh-Hans": "本地换算 Unix 文件权限（八进制 / 符号 / 权限位）",
      "zh-Hant": "本機換算 Unix 檔案權限（八進位／符號／權限位）",
      ja: "Unix 権限を 8 進・記号・ビットで変換",
      ko: "Unix 권한을 8진수·기호·비트로 변환",
      es: "Convierte modos Unix entre octal, simbólico y bits",
      fr: "Convertissez les modes Unix (octal, symbolique, bits)",
      de: "Unix-Modi zwischen oktal, symbolisch und Bits umwandeln",
      "pt-BR": "Converta modos Unix entre octal, simbólico e bits",
      ru: "Перевод Unix-прав между восьмеричным, символьным видом и битами",
    },
  },
  "cert-lab": {
    title: {
      en: "Certificate Lab",
      "zh-Hans": "证书查看",
      "zh-Hant": "憑證檢視",
      ja: "証明書ラボ",
      ko: "인증서 랩",
      es: "Certificate Lab",
      fr: "Certificate Lab",
      de: "Certificate Lab",
      "pt-BR": "Certificate Lab",
      ru: "Certificate Lab",
    },
    description: {
      en: "Inspect PEM certificates, validity, fingerprints, and SANs locally",
      "zh-Hans": "本地查看 PEM 证书、有效期、指纹与 SAN",
      "zh-Hant": "本機檢視 PEM 憑證、有效期、指紋與 SAN",
      ja: "PEM 証明書・有効期限・指紋・SAN をローカル確認",
      ko: "PEM 인증서·유효기간·지문·SAN을 로컬에서 확인",
      es: "Inspecciona certificados PEM, validez, huellas y SAN en local",
      fr: "Inspectez certificats PEM, validité, empreintes et SAN en local",
      de: "PEM-Zertifikate, Gültigkeit, Fingerprints und SANs lokal prüfen",
      "pt-BR": "Inspecione certificados PEM, validade, fingerprints e SAN localmente",
      ru: "Локальный разбор PEM-сертификатов, сроков, отпечатков и SAN",
    },
  },
  "text-lab": {
    title: {
      en: "Text Lab",
      "zh-Hans": "文本处理",
      "zh-Hant": "文字處理",
      ja: "テキストラボ",
      ko: "텍스트 랩",
      es: "Text Lab",
      fr: "Text Lab",
      de: "Text Lab",
      "pt-BR": "Text Lab",
      ru: "Text Lab",
    },
    description: {
      en: "Trim, dedupe, sort, and transform text lines locally",
      "zh-Hans": "本地对文本行去空白、去重、排序与大小写转换",
      "zh-Hant": "本機對文字行去空白、去重、排序與大小寫轉換",
      ja: "テキスト行の整形・重複削除・ソートをローカル実行",
      ko: "텍스트 줄 정리·중복 제거·정렬을 로컬에서 처리",
      es: "Recorta, deduplica, ordena y transforma líneas en local",
      fr: "Nettoyez, dédupliquez, triez et transformez des lignes en local",
      de: "Zeilen lokal trimmen, deduplizieren, sortieren und umwandeln",
      "pt-BR": "Ajuste, remova duplicatas, ordene e transforme linhas localmente",
      ru: "Локально чистите, дедуплицируйте и сортируйте строки текста",
    },
  },
  "curl-lab": {
    title: {
      en: "cURL Lab",
      "zh-Hans": "cURL 实验室",
      "zh-Hant": "cURL 實驗室",
      ja: "cURL ラボ",
      ko: "cURL 랩",
      es: "cURL Lab",
      fr: "cURL Lab",
      de: "cURL Lab",
      "pt-BR": "cURL Lab",
      ru: "cURL Lab",
    },
    description: {
      en: "Visually edit HTTP requests and convert to or from cURL",
      "zh-Hans": "可视化编辑 HTTP 请求，与 cURL 互相转换",
      "zh-Hant": "視覺化編輯 HTTP 請求，與 cURL 互相轉換",
      ja: "HTTP リクエストを可視化編集し cURL と相互変換",
      ko: "HTTP 요청을 시각적으로 편집하고 cURL과 상호 변환",
      es: "Edita peticiones HTTP visualmente y convierte desde/hacia cURL",
      fr: "Éditez des requêtes HTTP visuellement et convertissez depuis/vers cURL",
      de: "HTTP-Requests visuell bearbeiten und von/nach cURL konvertieren",
      "pt-BR": "Edite requisições HTTP visualmente e converta de/para cURL",
      ru: "Визуально редактируйте HTTP-запросы и конвертируйте в/из cURL",
    },
  },
  "connection-trace": {
    title: {
      en: "Connection Trace",
      "zh-Hans": "连接追踪",
      "zh-Hant": "連線追蹤",
      ja: "接続トレース",
      ko: "연결 추적",
      es: "Connection Trace",
      fr: "Connection Trace",
      de: "Connection Trace",
      "pt-BR": "Connection Trace",
      ru: "Connection Trace",
    },
    description: {
      en: "Trace DNS lookup and HTTP/TLS connection timing for a host",
      "zh-Hans": "追踪主机的 DNS 解析与 HTTP/TLS 连接耗时",
      "zh-Hant": "追蹤主機的 DNS 解析與 HTTP/TLS 連線耗時",
      ja: "ホストの DNS と HTTP/TLS 接続タイミングを追跡",
      ko: "호스트의 DNS·HTTP/TLS 연결 시간을 추적",
      es: "Rastrea DNS y tiempos de conexión HTTP/TLS de un host",
      fr: "Tracez DNS et timings de connexion HTTP/TLS d’un hôte",
      de: "DNS- und HTTP/TLS-Verbindungszeiten eines Hosts verfolgen",
      "pt-BR": "Rastreie DNS e tempos de conexão HTTP/TLS de um host",
      ru: "Трассировка DNS и времени HTTP/TLS-подключения хоста",
    },
  },
};

export function discoverToolIds() {
  return Object.keys(pageModules)
    .map((path) => path.match(/\/tools\/([^/]+)\//)?.[1])
    .filter((id) => id && !id.startsWith("_"))
    .sort((left, right) => {
      const leftRank = preferredOrder.indexOf(left);
      const rightRank = preferredOrder.indexOf(right);
      if (leftRank === -1 && rightRank === -1) return left.localeCompare(right);
      if (leftRank === -1) return 1;
      if (rightRank === -1) return -1;
      return leftRank - rightRank;
    });
}

function pickLocale(map, locale) {
  if (!map) return "";
  return map[locale] || map.en || Object.values(map)[0] || "";
}

export function listTools(locale = "en") {
  return discoverToolIds().map((id) => {
    const meta = toolMeta[id];
    return {
      id,
      title: pickLocale(meta?.title, locale) || id,
      description: pickLocale(meta?.description, locale),
      href: `./tools/${id}/`,
    };
  });
}
