import fs from "node:fs";
import path from "node:path";

const file = new URL("../Resources/Localizable.xcstrings", import.meta.url);
const root = path.resolve(import.meta.dirname, "..");
const catalog = JSON.parse(fs.readFileSync(file, "utf8"));
const values = {
  "%@ found so far": ["目前已发现 %@", "目前已發現 %@", "現在までに %@ を検出", "지금까지 %@ 발견", "%@ encontrados hasta ahora", "%@ trouvés jusqu’à présent", "Bisher %@ gefunden", "%@ encontrados até agora", "Найдено: %@"],
  "%lld / %lld": ["%lld / %lld", "%lld / %lld", "%lld / %lld", "%lld / %lld", "%lld / %lld", "%lld / %lld", "%lld / %lld", "%lld / %lld", "%lld / %lld"],
  "A VPN or TUN interface is active. Some destinations may bypass the default interface through more specific routes.": ["VPN 或 TUN 接口处于活动状态。部分目标可能通过更具体的路由绕过默认接口。", "VPN 或 TUN 介面處於活動狀態。部分目的地可能透過更明確的路由繞過預設介面。", "VPN または TUN インターフェイスが有効です。一部の宛先は、より優先度の高い経路でデフォルトインターフェイスを迂回する場合があります。", "VPN 또는 TUN 인터페이스가 활성 상태입니다. 일부 대상은 더 구체적인 경로를 통해 기본 인터페이스를 우회할 수 있습니다.", "Hay una interfaz VPN o TUN activa. Algunos destinos pueden omitir la interfaz predeterminada mediante rutas más específicas.", "Une interface VPN ou TUN est active. Certaines destinations peuvent contourner l’interface par défaut via des routes plus spécifiques.", "Eine VPN- oder TUN-Schnittstelle ist aktiv. Einige Ziele können die Standardschnittstelle über spezifischere Routen umgehen.", "Uma interface VPN ou TUN está ativa. Alguns destinos podem ignorar a interface padrão por rotas mais específicas.", "Активен интерфейс VPN или TUN. Некоторые адреса могут обходить интерфейс по умолчанию по более точным маршрутам."],
  "Check Route": ["检查路由", "檢查路由", "経路を確認", "경로 확인", "Comprobar ruta", "Vérifier la route", "Route prüfen", "Verificar rota", "Проверить маршрут"],
  "Default": ["默认", "預設", "デフォルト", "기본값", "Predeterminado", "Par défaut", "Standard", "Padrão", "По умолчанию"],
  "Deselect All": ["取消全选", "取消全選", "すべて選択解除", "모두 선택 해제", "Deseleccionar todo", "Tout désélectionner", "Auswahl aufheben", "Desmarcar tudo", "Снять выделение"],
  "Destination": ["目标", "目的地", "宛先", "대상", "Destino", "Destination", "Ziel", "Destino", "Назначение"],
  "example.com or 1.1.1.1": ["example.com 或 1.1.1.1", "example.com 或 1.1.1.1", "example.com または 1.1.1.1", "example.com 또는 1.1.1.1", "example.com o 1.1.1.1", "example.com ou 1.1.1.1", "example.com oder 1.1.1.1", "example.com ou 1.1.1.1", "example.com или 1.1.1.1"],
  "Family": ["地址族", "位址系列", "アドレスファミリー", "주소 체계", "Familia", "Famille", "Adressfamilie", "Família", "Семейство"],
  "Flags": ["标志", "旗標", "フラグ", "플래그", "Indicadores", "Indicateurs", "Flags", "Sinalizadores", "Флаги"],
  "Gateway": ["网关", "閘道", "ゲートウェイ", "게이트웨이", "Puerta de enlace", "Passerelle", "Gateway", "Gateway", "Шлюз"],
  "Gateway %@": ["网关 %@", "閘道 %@", "ゲートウェイ %@", "게이트웨이 %@", "Puerta de enlace %@", "Passerelle %@", "Gateway %@", "Gateway %@", "Шлюз %@"],
  "Inspecting interfaces, processes, routes, and proxy settings locally": ["正在本机检查接口、进程、路由和代理设置", "正在本機檢查介面、程序、路由和代理設定", "インターフェイス、プロセス、経路、プロキシ設定をローカルで確認中", "인터페이스, 프로세스, 경로 및 프록시 설정을 로컬에서 확인 중", "Inspeccionando localmente interfaces, procesos, rutas y ajustes de proxy", "Inspection locale des interfaces, processus, routes et réglages de proxy", "Schnittstellen, Prozesse, Routen und Proxy-Einstellungen werden lokal geprüft", "Inspecionando localmente interfaces, processos, rotas e ajustes de proxy", "Локальная проверка интерфейсов, процессов, маршрутов и настроек прокси"],
  "Interface": ["接口", "介面", "インターフェイス", "인터페이스", "Interfaz", "Interface", "Schnittstelle", "Interface", "Интерфейс"],
  "Local": ["本地", "本機", "ローカル", "로컬", "Local", "Local", "Lokal", "Local", "Локальный"],
  "Network Data Unavailable": ["网络数据不可用", "網路資料無法使用", "ネットワークデータを利用できません", "네트워크 데이터를 사용할 수 없음", "Datos de red no disponibles", "Données réseau indisponibles", "Netzwerkdaten nicht verfügbar", "Dados de rede indisponíveis", "Сетевые данные недоступны"],
  "No Active Connections": ["没有活动连接", "沒有活動連線", "アクティブな接続はありません", "활성 연결 없음", "No hay conexiones activas", "Aucune connexion active", "Keine aktiven Verbindungen", "Nenhuma conexão ativa", "Нет активных соединений"],
  "No Process Traffic": ["没有进程流量", "沒有程序流量", "プロセス通信量はありません", "프로세스 트래픽 없음", "No hay tráfico de procesos", "Aucun trafic de processus", "Kein Prozessdatenverkehr", "Nenhum tráfego de processos", "Нет трафика процессов"],
  "Reading network activity…": ["正在读取网络活动…", "正在讀取網路活動…", "ネットワークアクティビティを読み込み中…", "네트워크 활동 읽는 중…", "Leyendo la actividad de red…", "Lecture de l’activité réseau…", "Netzwerkaktivität wird gelesen…", "Lendo a atividade de rede…", "Чтение сетевой активности…"],
  "Remote": ["远程", "遠端", "リモート", "원격", "Remoto", "Distant", "Remote", "Remoto", "Удалённый"],
  "Select All": ["全选", "全選", "すべて選択", "모두 선택", "Seleccionar todo", "Tout sélectionner", "Alle auswählen", "Selecionar tudo", "Выбрать всё"],
  "State": ["状态", "狀態", "状態", "상태", "Estado", "État", "Status", "Estado", "Состояние"],
  "Total": ["总计", "總計", "合計", "합계", "Total", "Total", "Gesamt", "Total", "Всего"],
  "Traffic appears after an app sends or receives network data": ["应用发送或接收网络数据后，流量会显示在这里", "App 傳送或接收網路資料後，流量會顯示在這裡", "アプリがネットワークデータを送受信すると通信量が表示されます", "앱이 네트워크 데이터를 보내거나 받으면 트래픽이 표시됩니다", "El tráfico aparece cuando una app envía o recibe datos de red", "Le trafic apparaît lorsqu’une app envoie ou reçoit des données réseau", "Datenverkehr erscheint, sobald eine App Netzwerkdaten sendet oder empfängt", "O tráfego aparece quando um app envia ou recebe dados de rede", "Трафик появится после отправки или получения сетевых данных приложением"],
  "Getting ready…": ["正在准备…", "正在準備…", "準備中…", "준비 중…", "Preparando…", "Préparation…", "Vorbereitung…", "Preparando…", "Подготовка…"],
  "Reading network activity, routes, and proxy settings…": ["正在读取网络活动、路由和代理设置…", "正在讀取網路活動、路由和代理設定…", "ネットワークアクティビティ、経路、プロキシ設定を読み込み中…", "네트워크 활동, 경로 및 프록시 설정 읽는 중…", "Leyendo la actividad de red, las rutas y los ajustes de proxy…", "Lecture de l’activité réseau, des routes et des réglages de proxy…", "Netzwerkaktivität, Routen und Proxy-Einstellungen werden gelesen…", "Lendo a atividade de rede, as rotas e os ajustes de proxy…", "Чтение сетевой активности, маршрутов и настроек прокси…"],
  "%lld active connections found.": ["发现 %lld 个活动连接。", "發現 %lld 個活動連線。", "%lld 件のアクティブな接続が見つかりました。", "활성 연결 %lld개를 찾았습니다.", "Se encontraron %lld conexiones activas.", "%lld connexions actives trouvées.", "%lld aktive Verbindungen gefunden.", "Foram encontradas %lld conexões ativas.", "Найдено активных соединений: %lld."],
  "Checking app caches…": ["正在检查应用缓存…", "正在檢查 App 快取…", "アプリのキャッシュを確認中…", "앱 캐시 확인 중…", "Comprobando cachés de aplicaciones…", "Vérification des caches d’apps…", "App-Caches werden geprüft…", "Verificando caches de apps…", "Проверка кэшей приложений…"],
  "Checking developer logs…": ["正在检查开发日志…", "正在檢查開發日誌…", "開発ログを確認中…", "개발자 로그 확인 중…", "Comprobando registros de desarrollo…", "Vérification des journaux de développement…", "Entwicklerprotokolle werden geprüft…", "Verificando logs de desenvolvimento…", "Проверка журналов разработки…"],
  "Checking old installers…": ["正在检查旧安装包…", "正在檢查舊安裝程式…", "古いインストーラを確認中…", "오래된 설치 파일 확인 중…", "Comprobando instaladores antiguos…", "Vérification des anciens programmes d’installation…", "Alte Installationsdateien werden geprüft…", "Verificando instaladores antigos…", "Проверка старых установщиков…"],
  "Checking dependency libraries…": ["正在检查依赖库…", "正在檢查相依套件庫…", "依存ライブラリを確認中…", "종속성 라이브러리 확인 중…", "Comprobando bibliotecas de dependencias…", "Vérification des bibliothèques de dépendances…", "Abhängigkeitsbibliotheken werden geprüft…", "Verificando bibliotecas de dependências…", "Проверка библиотек зависимостей…"],
  "Checking build caches…": ["正在检查构建缓存…", "正在檢查建置快取…", "ビルドキャッシュを確認中…", "빌드 캐시 확인 중…", "Comprobando cachés de compilación…", "Vérification des caches de compilation…", "Build-Caches werden geprüft…", "Verificando caches de build…", "Проверка кэшей сборки…"],
  "Checking simulator data…": ["正在检查模拟器数据…", "正在檢查模擬器資料…", "シミュレータデータを確認中…", "시뮬레이터 데이터 확인 중…", "Comprobando datos del simulador…", "Vérification des données du simulateur…", "Simulatordaten werden geprüft…", "Verificando dados do simulador…", "Проверка данных симулятора…"],
  "Checking leftover app data…": ["正在检查应用残留数据…", "正在檢查 App 殘留資料…", "アプリの残留データを確認中…", "앱 잔여 데이터 확인 중…", "Comprobando datos residuales de aplicaciones…", "Vérification des données résiduelles d’apps…", "Verbliebene App-Daten werden geprüft…", "Verificando dados residuais de apps…", "Проверка оставшихся данных приложений…"],
  "Looking around…": ["正在检查…", "正在檢查…", "確認中…", "확인 중…", "Buscando…", "Vérification…", "Überprüfung…", "Verificando…", "Проверка…"],
  "%lld connections cached; refresh to scan again.": ["已缓存 %lld 个连接；刷新可重新扫描。", "已快取 %lld 個連線；重新整理可再次掃描。", "%lld 件の接続をキャッシュ済みです。更新すると再スキャンします。", "연결 %lld개가 캐시되었습니다. 새로 고치면 다시 검사합니다.", "Hay %lld conexiones en caché; actualiza para volver a analizar.", "%lld connexions sont en cache ; actualisez pour relancer l’analyse.", "%lld Verbindungen zwischengespeichert; zum erneuten Scannen aktualisieren.", "%lld conexões em cache; atualize para verificar novamente.", "Соединений в кэше: %lld; обновите для повторного сканирования."],
  "%lld apps": ["%lld 个应用", "%lld 個 App", "%lld 個のアプリ", "앱 %lld개", "%lld aplicaciones", "%lld apps", "%lld Apps", "%lld apps", "Приложений: %lld"],
  "Unable to read active connections.": ["无法读取活动连接。", "無法讀取活動連線。", "アクティブな接続を読み取れません。", "활성 연결을 읽을 수 없습니다.", "No se pueden leer las conexiones activas.", "Impossible de lire les connexions actives.", "Aktive Verbindungen können nicht gelesen werden.", "Não foi possível ler as conexões ativas.", "Не удалось прочитать активные соединения."],
  "Unable to read active connections: %@": ["无法读取活动连接：%@", "無法讀取活動連線：%@", "アクティブな接続を読み取れません：%@", "활성 연결을 읽을 수 없습니다: %@", "No se pueden leer las conexiones activas: %@", "Impossible de lire les connexions actives : %@", "Aktive Verbindungen können nicht gelesen werden: %@", "Não foi possível ler as conexões ativas: %@", "Не удалось прочитать активные соединения: %@"],
  "Per-process traffic is unavailable.": ["无法获取各进程流量。", "無法取得各程序流量。", "プロセス別の通信量を利用できません。", "프로세스별 트래픽을 사용할 수 없습니다.", "El tráfico por proceso no está disponible.", "Le trafic par processus est indisponible.", "Datenverkehr pro Prozess ist nicht verfügbar.", "O tráfego por processo está indisponível.", "Трафик по процессам недоступен."],
  "Per-process traffic is unavailable: %@": ["无法获取各进程流量：%@", "無法取得各程序流量：%@", "プロセス別の通信量を利用できません：%@", "프로세스별 트래픽을 사용할 수 없습니다: %@", "El tráfico por proceso no está disponible: %@", "Le trafic par processus est indisponible : %@", "Datenverkehr pro Prozess ist nicht verfügbar: %@", "O tráfego por processo está indisponível: %@", "Трафик по процессам недоступен: %@"],
  "Memory Usage": ["内存使用量", "記憶體使用量", "メモリ使用量", "메모리 사용량", "Uso de memoria", "Utilisation de la mémoire", "Speichernutzung", "Uso de memória", "Использование памяти"],
  "Critical": ["严重", "嚴重", "重大", "위험", "Crítico", "Critique", "Kritisch", "Crítico", "Критическое"],
  "Sift": ["Sift", "Sift", "Sift", "Sift", "Sift", "Sift", "Sift", "Sift", "Sift"],
  "Home": ["首页", "首頁", "ホーム", "홈", "Inicio", "Accueil", "Start", "Início", "Главная"],
  "Cleanup": ["垃圾清理", "垃圾清理", "クリーン", "정리", "Limpieza", "Nettoyage", "Bereinigen", "Limpeza", "Очистка"],
  "Apps": ["应用", "應用程式", "アプリ", "앱", "Aplicaciones", "Applications", "Apps", "Aplicativos", "Приложения"],
  "Storage": ["存储", "儲存", "ストレージ", "저장 공간", "Almacenamiento", "Stockage", "Speicher", "Armazenamento", "Хранилище"],
  "Performance": ["性能监控", "效能監控", "パフォーマンス", "성능", "Rendimiento", "Performances", "Leistung", "Desempenho", "Ресурсы"],
  "App Traffic": ["应用流量", "App 流量", "アプリ通信量", "앱 트래픽", "Tráfico de aplicaciones", "Trafic des applications", "App-Datenverkehr", "Tráfego de apps", "Трафик приложений"],
  "Active Connections": ["活动连接", "使用中的連線", "アクティブな接続", "활성 연결", "Conexiones activas", "Connexions actives", "Aktive Verbindungen", "Conexões ativas", "Активные соединения"],
  "Listening Ports": ["监听端口", "監聽連接埠", "待受ポート", "수신 대기 포트", "Puertos en escucha", "Ports en écoute", "Listening-Ports", "Portas em escuta", "Прослушиваемые порты"],
  "A system proxy is enabled. Route lookup shows the Mac's outbound route; proxied apps connect to the local proxy first.": ["已启用系统代理。路由查询显示 Mac 的出口路由；使用代理的 App 会先连接本地代理。", "已啟用系統代理。路由查詢顯示 Mac 的出口路由；使用代理的 App 會先連接本機代理。", "システムプロキシが有効です。経路検索には Mac の外向き経路が表示され、プロキシを使うアプリは先にローカルプロキシへ接続します。", "시스템 프록시가 활성화되어 있습니다. 경로 조회는 Mac의 외부 경로를 표시하며, 프록시 앱은 먼저 로컬 프록시에 연결합니다.", "Hay un proxy del sistema activo. La consulta de ruta muestra la salida del Mac; las apps con proxy se conectan primero al proxy local.", "Un proxy système est activé. La recherche d’itinéraire affiche la sortie du Mac ; les apps utilisant le proxy se connectent d’abord au proxy local.", "Ein Systemproxy ist aktiv. Die Routensuche zeigt den Ausgangspfad des Macs; Apps mit Proxy verbinden sich zuerst mit dem lokalen Proxy.", "Um proxy do sistema está ativo. A consulta de rota mostra a saída do Mac; apps com proxy se conectam primeiro ao proxy local.", "Включён системный прокси. Поиск маршрута показывает выходной маршрут Mac; приложения с прокси сначала подключаются к локальному прокси."],
  "Ports": ["端口", "連接埠", "ポート", "포트", "Puertos", "Ports", "Ports", "Portas", "Порты"],
  "System": ["系统", "系統", "システム", "시스템", "Sistema", "Système", "System", "Sistema", "Система"],
  "Settings": ["设置", "設定", "設定", "설정", "Ajustes", "Réglages", "Einstellungen", "Ajustes", "Настройки"],
  "Open Sift": ["打开 Sift", "開啟 Sift", "Sift を開く", "Sift 열기", "Abrir Sift", "Ouvrir Sift", "Sift öffnen", "Abrir Sift", "Открыть Sift"],
  "Quit": ["退出", "退出", "終了", "종료", "Salir", "Quitter", "Beenden", "Sair", "Выйти"],
  "Keep in Menu Bar": ["常驻菜单栏", "常駐選單列", "メニューバーに常駐", "메뉴 막대에 유지", "Mantener en la barra de menús", "Garder dans la barre des menus", "In der Menüleiste anzeigen", "Manter na barra de menus", "Показывать в строке меню"],
  "Show CPU, memory, network speed, and quick actions in the menu bar": ["在菜单栏中查看 CPU、内存、网速和快捷操作", "在選單列中查看 CPU、記憶體、網速和快速操作", "メニューバーで CPU、メモリ、通信速度、クイック操作を表示します", "메뉴 막대에서 CPU, 메모리, 네트워크 속도 및 빠른 작업을 표시합니다", "Muestra CPU, memoria, velocidad de red y acciones rápidas en la barra de menús", "Affiche le CPU, la mémoire, le débit réseau et des actions rapides dans la barre des menus", "Zeigt CPU, Arbeitsspeicher, Netzwerkgeschwindigkeit und Schnellaktionen in der Menüleiste", "Mostra CPU, memória, velocidade da rede e ações rápidas na barra de menus", "Показывает ЦП, память, скорость сети и быстрые действия в строке меню"],
  "Feedback": ["反馈", "意見回饋", "フィードバック", "피드백", "Comentarios", "Avis", "Feedback", "Feedback", "Отзыв"],
  "Follow System": ["跟随系统", "跟隨系統", "システム設定", "시스템 설정", "Seguir el sistema", "Selon le système", "Systemeinstellung", "Seguir o sistema", "Как в системе"],
  "Found": ["已发现", "已發現", "検出", "발견됨", "Encontrado", "Trouvé", "Gefunden", "Encontrado", "Найдено"],
  "Safe to Clean": ["可安全清理", "可安全清理", "安全に削除可能", "안전하게 정리 가능", "Seguro para limpiar", "Nettoyage sûr", "Sicher zu bereinigen", "Seguro para limpar", "Можно безопасно очистить"],
  "%lld selected by default": ["默认选择 %lld 项", "預設選取 %lld 項", "%lld 件をデフォルトで選択", "기본 선택 %lld개", "%lld seleccionados de forma predeterminada", "%lld sélectionnés par défaut", "%lld standardmäßig ausgewählt", "%lld selecionados por padrão", "%lld выбрано по умолчанию"],
  "%lld not selected": ["%lld 项未选择", "%lld 項未選取", "%lld 件は未選択", "%lld개 선택 안 함", "%lld no seleccionados", "%lld non sélectionnés", "%lld nicht ausgewählt", "%lld não selecionados", "%lld не выбрано"],
  "Leftovers": ["卸载残留", "解除安裝殘留", "アンインストール残留", "제거 잔여 파일", "Restos", "Résidus", "Überreste", "Resíduos", "Остатки"],
  "%lld apps · %lld possible leftovers": ["%lld 个应用 · %lld 组可能残留", "%lld 個 App · %lld 組可能殘留", "%lld 個のアプリ・%lld 件の残留候補", "앱 %lld개 · 잔여 파일 후보 %lld개", "%lld aplicaciones · %lld posibles restos", "%lld apps · %lld résidus possibles", "%lld Apps · %lld mögliche Überreste", "%lld apps · %lld possíveis resíduos", "%lld приложений · %lld возможных остатков"],
  "Possible Uninstall Leftovers": ["可能的卸载残留", "可能的解除安裝殘留", "アンインストール残留の候補", "제거 잔여 파일 후보", "Posibles restos de desinstalación", "Résidus de désinstallation possibles", "Mögliche Deinstallationsreste", "Possíveis resíduos de desinstalação", "Возможные остатки после удаления"],
  "Sift found app-style identifiers with no matching installed app. These are review-only because helpers and command-line tools can own similar files.": ["Sift 发现了一些没有对应已安装应用的 App 标识符。辅助程序和命令行工具也可能拥有类似文件，因此这里只供检查。", "Sift 發現了一些沒有對應已安裝 App 的識別碼。輔助程式和命令列工具也可能擁有類似檔案，因此這裡只供檢查。", "インストール済みアプリに一致しないアプリ形式の識別子が見つかりました。ヘルパーやコマンドラインツールも同様のファイルを所有する場合があるため、確認専用です。", "설치된 앱과 일치하지 않는 앱 형식 식별자를 찾았습니다. 도우미 및 명령줄 도구도 비슷한 파일을 소유할 수 있으므로 검토용으로만 표시됩니다.", "Sift encontró identificadores de aplicación sin una app instalada correspondiente. Solo se muestran para revisión porque los auxiliares y las herramientas de línea de comandos pueden tener archivos similares.", "Sift a trouvé des identifiants d’app sans application installée correspondante. Ils sont uniquement à vérifier, car des utilitaires et outils en ligne de commande peuvent posséder des fichiers similaires.", "Sift hat App-Kennungen ohne passende installierte App gefunden. Sie dienen nur zur Prüfung, da Hilfsprogramme und Befehlszeilentools ähnliche Dateien besitzen können.", "O Sift encontrou identificadores de app sem um aplicativo instalado correspondente. Eles são apenas para revisão, pois auxiliares e ferramentas de linha de comando podem ter arquivos semelhantes.", "Sift обнаружил идентификаторы приложений без соответствующего установленного приложения. Они показаны только для проверки, поскольку похожие файлы могут принадлежать вспомогательным и консольным программам."],
  "No possible app leftovers found": ["未发现可能的应用残留", "未發現可能的 App 殘留", "アプリの残留候補はありません", "앱 잔여 파일 후보 없음", "No se encontraron posibles restos de aplicaciones", "Aucun résidu d’app possible trouvé", "Keine möglichen App-Überreste gefunden", "Nenhum possível resíduo de app encontrado", "Возможных остатков приложений не найдено"],
  "Only identifier-based caches, preferences, saved state, logs, and sandbox containers are checked.": ["仅检查以 App 标识符命名的缓存、偏好设置、保存状态、日志和沙盒容器。", "僅檢查以 App 識別碼命名的快取、偏好設定、儲存狀態、日誌和沙盒容器。", "識別子ベースのキャッシュ、環境設定、保存状態、ログ、サンドボックスコンテナのみを確認します。", "식별자 기반 캐시, 환경설정, 저장 상태, 로그 및 샌드박스 컨테이너만 확인합니다.", "Solo se comprueban cachés, preferencias, estados guardados, registros y contenedores de sandbox basados en identificadores.", "Seuls les caches, préférences, états enregistrés, journaux et conteneurs sandbox basés sur un identifiant sont vérifiés.", "Geprüft werden nur kennungsbasierte Caches, Einstellungen, gespeicherte Zustände, Protokolle und Sandbox-Container.", "Apenas caches, preferências, estados salvos, logs e contêineres de sandbox baseados em identificadores são verificados.", "Проверяются только кэши, настройки, сохранённые состояния, журналы и контейнеры песочницы с идентификаторами."],
  "%lld related files · Review only": ["%lld 个相关文件 · 仅供检查", "%lld 個相關檔案 · 僅供檢查", "%lld 個の関連ファイル・確認のみ", "관련 파일 %lld개 · 검토 전용", "%lld archivos relacionados · Solo revisión", "%lld fichiers associés · Vérification uniquement", "%lld zugehörige Dateien · Nur prüfen", "%lld arquivos relacionados · Apenas revisão", "%lld связанных файлов · Только проверка"],
  "Reveal in Finder": ["在访达中显示", "在 Finder 中顯示", "Finder に表示", "Finder에서 보기", "Mostrar en Finder", "Afficher dans le Finder", "Im Finder zeigen", "Mostrar no Finder", "Показать в Finder"],
  "%lld apps and %lld possible leftovers found.": ["发现 %lld 个应用和 %lld 组可能残留。", "發現 %lld 個 App 和 %lld 組可能殘留。", "%lld 個のアプリと %lld 件の残留候補が見つかりました。", "앱 %lld개와 잔여 파일 후보 %lld개를 찾았습니다.", "Se encontraron %lld aplicaciones y %lld posibles restos.", "%lld apps et %lld résidus possibles trouvés.", "%lld Apps und %lld mögliche Überreste gefunden.", "%lld apps e %lld possíveis resíduos encontrados.", "Найдено приложений: %lld; возможных остатков: %lld."],
  "Checking command-line tools and possible leftovers…": ["正在检查命令行工具和可能残留…", "正在檢查命令列工具和可能殘留…", "コマンドラインツールと残留候補を確認中…", "명령줄 도구와 잔여 파일 후보 확인 중…", "Comprobando herramientas de línea de comandos y posibles restos…", "Vérification des outils en ligne de commande et des résidus possibles…", "Befehlszeilentools und mögliche Überreste werden geprüft…", "Verificando ferramentas de linha de comando e possíveis resíduos…", "Проверка консольных инструментов и возможных остатков…"],
  "Rule %lld of %lld": ["第 %lld/%lld 条规则", "第 %lld/%lld 條規則", "ルール %lld/%lld", "규칙 %lld/%lld", "Regla %lld de %lld", "Règle %lld sur %lld", "Regel %lld von %lld", "Regra %lld de %lld", "Правило %lld из %lld"],
  "Uninstall Leftovers": ["卸载残留", "解除安裝殘留", "アンインストール残留", "제거 잔여 파일", "Restos de desinstalación", "Résidus de désinstallation", "Deinstallationsreste", "Resíduos de desinstalação", "Остатки после удаления"],
  "Files whose app is no longer installed; review them before moving them to Trash.": ["对应应用已不存在的文件；移入废纸篓前请逐项检查。", "對應 App 已不存在的檔案；移入垃圾桶前請逐項檢查。", "対応するアプリがインストールされていないファイルです。ゴミ箱へ移動する前に確認してください。", "해당 앱이 더 이상 설치되어 있지 않은 파일입니다. 휴지통으로 옮기기 전에 확인하세요.", "Archivos cuya app ya no está instalada; revíselos antes de moverlos a la Papelera.", "Fichiers dont l’app n’est plus installée ; vérifiez-les avant de les placer dans la Corbeille.", "Dateien, deren App nicht mehr installiert ist; vor dem Verschieben in den Papierkorb prüfen.", "Arquivos cujo app não está mais instalado; revise antes de mover para o Lixo.", "Файлы приложений, которые больше не установлены; проверьте их перед перемещением в Корзину."],
  "Checking command-line tools…": ["正在检查命令行工具…", "正在檢查命令列工具…", "コマンドラインツールを確認中…", "명령줄 도구 확인 중…", "Comprobando herramientas de línea de comandos…", "Vérification des outils en ligne de commande…", "Befehlszeilentools werden geprüft…", "Verificando ferramentas de linha de comando…", "Проверка консольных инструментов…"],
  "%lld apps found.": ["发现 %lld 个应用。", "發現 %lld 個 App。", "%lld 個のアプリが見つかりました。", "앱 %lld개를 찾았습니다.", "Se encontraron %lld aplicaciones.", "%lld apps trouvées.", "%lld Apps gefunden.", "%lld apps encontrados.", "Найдено приложений: %lld."],
  "Installed apps and command-line tools": ["已安装的应用和命令行工具", "已安裝的 App 和命令列工具", "インストール済みアプリとコマンドラインツール", "설치된 앱과 명령줄 도구", "Apps instaladas y herramientas de línea de comandos", "Apps installées et outils en ligne de commande", "Installierte Apps und Befehlszeilentools", "Apps instalados e ferramentas de linha de comando", "Установленные приложения и консольные инструменты"],
  "Checking app caches, preferences, logs, and containers…": ["正在检查应用缓存、偏好设置、日志和容器…", "正在檢查 App 快取、偏好設定、日誌和容器…", "アプリのキャッシュ、設定、ログ、コンテナを確認中…", "앱 캐시, 환경설정, 로그 및 컨테이너 확인 중…", "Comprobando cachés, preferencias, registros y contenedores de apps…", "Vérification des caches, préférences, journaux et conteneurs d’apps…", "App-Caches, Einstellungen, Protokolle und Container werden geprüft…", "Verificando caches, preferências, logs e contêineres de apps…", "Проверка кэшей, настроек, журналов и контейнеров приложений…"],
  "%lld possible leftovers need review": ["%lld 组可能残留需要检查", "%lld 組可能殘留需要檢查", "%lld 件の残留候補を確認", "잔여 파일 후보 %lld개 검토 필요", "%lld posibles restos para revisar", "%lld résidus possibles à vérifier", "%lld mögliche Überreste prüfen", "%lld possíveis resíduos para revisar", "Нужно проверить возможные остатки: %lld"],
  "Homebrew Download Cache": ["Homebrew 下载缓存", "Homebrew 下載快取", "Homebrew ダウンロードキャッシュ", "Homebrew 다운로드 캐시", "Caché de descargas de Homebrew", "Cache de téléchargement Homebrew", "Homebrew-Download-Cache", "Cache de downloads do Homebrew", "Кэш загрузок Homebrew"],
  "CocoaPods Cache": ["CocoaPods 缓存", "CocoaPods 快取", "CocoaPods キャッシュ", "CocoaPods 캐시", "Caché de CocoaPods", "Cache CocoaPods", "CocoaPods-Cache", "Cache do CocoaPods", "Кэш CocoaPods"],
  "Swift Package Manager Cache": ["Swift Package Manager 缓存", "Swift Package Manager 快取", "Swift Package Manager キャッシュ", "Swift Package Manager 캐시", "Caché de Swift Package Manager", "Cache Swift Package Manager", "Swift-Package-Manager-Cache", "Cache do Swift Package Manager", "Кэш Swift Package Manager"],
  "Yarn Download Cache": ["Yarn 下载缓存", "Yarn 下載快取", "Yarn ダウンロードキャッシュ", "Yarn 다운로드 캐시", "Caché de descargas de Yarn", "Cache de téléchargement Yarn", "Yarn-Download-Cache", "Cache de downloads do Yarn", "Кэш загрузок Yarn"],
  "Gradle Build Cache": ["Gradle 构建缓存", "Gradle 建置快取", "Gradle ビルドキャッシュ", "Gradle 빌드 캐시", "Caché de compilación de Gradle", "Cache de build Gradle", "Gradle-Build-Cache", "Cache de build do Gradle", "Кэш сборки Gradle"],
  "Android Tool Cache": ["Android 工具缓存", "Android 工具快取", "Android ツールキャッシュ", "Android 도구 캐시", "Caché de herramientas de Android", "Cache des outils Android", "Android-Tool-Cache", "Cache de ferramentas do Android", "Кэш инструментов Android"],
  "Apple Simulator Cache": ["Apple 模拟器缓存", "Apple 模擬器快取", "Apple シミュレータキャッシュ", "Apple 시뮬레이터 캐시", "Caché del simulador de Apple", "Cache du simulateur Apple", "Apple-Simulator-Cache", "Cache do simulador da Apple", "Кэш симулятора Apple"],
  "Downloaded formula and cask archives; installed packages in Cellar and Caskroom are not touched.": ["已下载的 formula 和 cask 安装包；不会处理 Cellar 和 Caskroom 中已安装的软件。", "已下載的 formula 和 cask 安裝包；不會處理 Cellar 和 Caskroom 中已安裝的軟體。", "ダウンロード済みの formula と cask アーカイブです。Cellar と Caskroom のインストール済みパッケージは削除しません。", "다운로드된 formula 및 cask 아카이브입니다. Cellar와 Caskroom의 설치된 패키지는 유지됩니다.", "Archivos descargados de fórmulas y casks; no se tocan los paquetes instalados en Cellar y Caskroom.", "Archives de formules et casks téléchargées ; les paquets installés dans Cellar et Caskroom sont conservés.", "Geladene Formula- und Cask-Archive; installierte Pakete in Cellar und Caskroom bleiben erhalten.", "Arquivos de fórmulas e casks baixados; pacotes instalados no Cellar e Caskroom são preservados.", "Загруженные архивы formula и cask; пакеты в Cellar и Caskroom не затрагиваются."],
  "Downloaded pod archives and specs can be fetched again; project Pods directories are not scanned.": ["已下载的 Pod 安装包和索引可重新获取；不扫描项目中的 Pods 目录。", "已下載的 Pod 安裝包和索引可重新取得；不掃描專案中的 Pods 目錄。", "ダウンロード済みの Pod アーカイブと spec は再取得可能です。プロジェクトの Pods はスキャンしません。", "다운로드된 Pod 아카이브와 spec은 다시 받을 수 있습니다. 프로젝트 Pods 폴더는 스캔하지 않습니다.", "Los archivos y especificaciones de pods pueden volver a descargarse; no se analizan las carpetas Pods de los proyectos.", "Les archives et specs de pods peuvent être retéléchargées ; les dossiers Pods des projets ne sont pas analysés.", "Pod-Archive und Specs können erneut geladen werden; Pods-Ordner in Projekten werden nicht gescannt.", "Arquivos e especificações de pods podem ser baixados novamente; pastas Pods dos projetos não são verificadas.", "Архивы и спецификации pods можно скачать заново; папки Pods в проектах не сканируются."],
  "Swift package metadata and downloads can be resolved again; project checkouts and source packages are preserved.": ["Swift 包元数据和下载内容可重新解析；保留项目检出内容和源码包。", "Swift 套件中繼資料和下載內容可重新解析；保留專案檢出內容和原始碼套件。", "Swift パッケージのメタデータとダウンロードは再解決できます。プロジェクトの checkout とソースは保持します。", "Swift 패키지 메타데이터와 다운로드는 다시 해결할 수 있습니다. 프로젝트 checkout과 소스는 유지됩니다.", "Los metadatos y descargas de paquetes Swift pueden resolverse de nuevo; se conservan los checkouts y fuentes de los proyectos.", "Les métadonnées et téléchargements Swift peuvent être résolus à nouveau ; les checkouts et sources des projets sont conservés.", "Swift-Paketmetadaten und Downloads können neu aufgelöst werden; Projekt-Checkouts und Quellen bleiben erhalten.", "Metadados e downloads de pacotes Swift podem ser resolvidos novamente; checkouts e fontes dos projetos são preservados.", "Метаданные и загрузки Swift-пакетов можно получить заново; checkout и исходники проектов сохраняются."],
  "Global Yarn download cache; project node_modules and offline mirrors are not scanned.": ["Yarn 全局下载缓存；不扫描项目 node_modules 和离线镜像。", "Yarn 全域下載快取；不掃描專案 node_modules 和離線鏡像。", "Yarn のグローバルダウンロードキャッシュです。プロジェクトの node_modules とオフラインミラーはスキャンしません。", "Yarn 전역 다운로드 캐시입니다. 프로젝트 node_modules와 오프라인 미러는 스캔하지 않습니다.", "Caché global de Yarn; no se analizan node_modules ni espejos sin conexión de los proyectos.", "Cache globale de Yarn ; les node_modules et miroirs hors ligne des projets ne sont pas analysés.", "Globaler Yarn-Download-Cache; node_modules und Offline-Mirrors in Projekten werden nicht gescannt.", "Cache global do Yarn; node_modules e espelhos offline dos projetos não são verificados.", "Глобальный кэш Yarn; node_modules и офлайн-зеркала проектов не сканируются."],
  "Gradle can rebuild or redownload these files, but the next Android or JVM build may be much slower.": ["Gradle 可以重建或重新下载这些文件，但下次 Android 或 JVM 构建可能明显变慢。", "Gradle 可以重建或重新下載這些檔案，但下次 Android 或 JVM 建置可能明顯變慢。", "Gradle で再生成または再ダウンロードできますが、次回の Android/JVM ビルドが大幅に遅くなる場合があります。", "Gradle이 다시 빌드하거나 다운로드할 수 있지만 다음 Android/JVM 빌드가 크게 느려질 수 있습니다.", "Gradle puede regenerar o descargar estos archivos, pero la próxima compilación Android o JVM puede ser mucho más lenta.", "Gradle peut recréer ou retélécharger ces fichiers, mais le prochain build Android ou JVM peut être bien plus lent.", "Gradle kann diese Dateien neu erstellen oder laden; der nächste Android- oder JVM-Build kann deutlich langsamer sein.", "O Gradle pode recriar ou baixar esses arquivos, mas o próximo build Android ou JVM pode ficar bem mais lento.", "Gradle может пересоздать или скачать эти файлы, но следующая сборка Android/JVM может быть значительно медленнее."],
  "Regenerable Android tool downloads and metadata; SDK platforms, emulators, and projects are not scanned.": ["可重新生成的 Android 工具下载内容和元数据；不扫描 SDK 平台、模拟器和项目。", "可重新生成的 Android 工具下載內容和中繼資料；不掃描 SDK 平台、模擬器和專案。", "再生可能な Android ツールのダウンロードとメタデータです。SDK、エミュレータ、プロジェクトはスキャンしません。", "다시 생성 가능한 Android 도구 다운로드와 메타데이터입니다. SDK, 에뮬레이터, 프로젝트는 스캔하지 않습니다.", "Descargas y metadatos regenerables de Android; no se analizan plataformas SDK, emuladores ni proyectos.", "Téléchargements et métadonnées Android régénérables ; les SDK, émulateurs et projets ne sont pas analysés.", "Neu erzeugbare Android-Tool-Downloads und Metadaten; SDKs, Emulatoren und Projekte werden nicht gescannt.", "Downloads e metadados regeneráveis do Android; SDKs, emuladores e projetos não são verificados.", "Восстанавливаемые загрузки и метаданные Android; SDK, эмуляторы и проекты не сканируются."],
  "Regenerable simulator caches only; simulator devices, installed runtimes, and app data are preserved.": ["仅扫描可重新生成的模拟器缓存；保留模拟器设备、已安装运行时和应用数据。", "僅掃描可重新生成的模擬器快取；保留模擬器裝置、已安裝執行環境和 App 資料。", "再生可能なシミュレータキャッシュのみです。デバイス、ランタイム、アプリデータは保持します。", "다시 생성 가능한 시뮬레이터 캐시만 스캔합니다. 기기, 런타임, 앱 데이터는 유지됩니다.", "Solo cachés regenerables del simulador; se conservan dispositivos, runtimes instalados y datos de apps.", "Uniquement les caches régénérables du simulateur ; appareils, runtimes installés et données d’apps sont conservés.", "Nur neu erzeugbare Simulator-Caches; Geräte, installierte Runtimes und App-Daten bleiben erhalten.", "Apenas caches regeneráveis do simulador; dispositivos, runtimes instalados e dados de apps são preservados.", "Только восстанавливаемые кэши симулятора; устройства, runtime и данные приложений сохраняются."],
};
const locales = ["zh-Hans", "zh-Hant", "ja", "ko", "es", "fr", "de", "pt-BR", "ru"];
for (const [key, translations] of Object.entries(values)) {
  const entry = catalog.strings[key] ??= {};
  entry.localizations ??= {};
  locales.forEach((locale, index) => {
    entry.localizations[locale] = { stringUnit: { state: "translated", value: translations[index] } };
  });
}

function swiftFiles(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const target = path.join(directory, entry.name);
    if (entry.isDirectory()) return swiftFiles(target);
    return entry.isFile() && entry.name.endsWith(".swift") ? [target] : [];
  });
}

// Runtime localization helpers are invisible to Xcode's extractor. Keep only
// catalog keys that still occur as Swift string literals, and remove genuinely
// dead stale entries so the catalog remains warning-free without hiding debris.
const referencedLiterals = new Set();
for (const sourceDirectory of [path.join(root, "App/Sources"), path.join(root, "Sources")]) {
  for (const sourceFile of swiftFiles(sourceDirectory)) {
    const source = fs.readFileSync(sourceFile, "utf8");
    for (const match of source.matchAll(/"((?:\\.|[^"\\])*)"/g)) {
      try {
        referencedLiterals.add(JSON.parse(`"${match[1]}"`));
      } catch {
        // Ignore interpolated or otherwise non-JSON Swift literals.
      }
    }
  }
}
for (const [key, entry] of Object.entries(catalog.strings)) {
  if (entry.extractionState !== "stale") continue;
  if (referencedLiterals.has(key)) entry.extractionState = "manual";
  else delete catalog.strings[key];
}

// Removed features: do not retain obsolete translations as manual entries.
for (const key of [
  "Allow paths, file types, sizes, and process details to be sent for analysis",
  "Share Technical Metadata",
  "Uninstall",
  "Storage Analysis",
  "Port Manager",
  "Login Items & Extensions",
  "%lld conservative rules · age limits protect recent files",
  "What Sift Checked",
  "Only old or regenerable files are candidates; recent files and installed dependencies are excluded.",
  "%lld/%lld categories found",
  "Nothing found",
  "%lld+ days · %@",
  "Safe",
  ""
]) {
  delete catalog.strings[key];
}
fs.writeFileSync(file, `${JSON.stringify(catalog, null, 2)}\n`);
