export const labels = {
  en: { system: "System", systemHosts: "System Hosts", systemHint: "Current /etc/hosts · Read only", shared: "Shared", sharedName: "Shared Configuration", sharedHint: "Always included", environments: "Environments", add: "Add", activate: "Activate", active: "Active", delete: "Delete", empty: "Add one mapping per line", development: "Development", testing: "Testing", production: "Production" },
  "zh-Hans": { system: "系统", systemHosts: "系统 Hosts", systemHint: "当前 /etc/hosts · 只读", shared: "公共", sharedName: "公共配置", sharedHint: "始终包含", environments: "环境", add: "新增", activate: "启用", active: "已启用", delete: "删除", empty: "每行添加一条映射", development: "开发环境", testing: "测试环境", production: "生产环境" },
  "zh-Hant": { system: "系統", systemHosts: "系統 Hosts", systemHint: "目前 /etc/hosts · 唯讀", shared: "共用", sharedName: "共用設定", sharedHint: "一律包含", environments: "環境", add: "新增", activate: "啟用", active: "已啟用", delete: "刪除", empty: "每行新增一條對應", development: "開發環境", testing: "測試環境", production: "正式環境" },
  ja: { system: "システム", systemHosts: "システム Hosts", systemHint: "現在の /etc/hosts · 読み取り専用", shared: "共有", sharedName: "共有設定", sharedHint: "常に含める", environments: "環境", add: "追加", activate: "有効化", active: "有効", delete: "削除", empty: "1 行に 1 つのマッピングを追加", development: "開発環境", testing: "テスト環境", production: "本番環境" },
  ko: { system: "시스템", systemHosts: "시스템 Hosts", systemHint: "현재 /etc/hosts · 읽기 전용", shared: "공유", sharedName: "공유 설정", sharedHint: "항상 포함", environments: "환경", add: "추가", activate: "활성화", active: "활성", delete: "삭제", empty: "한 줄에 하나의 매핑을 추가하세요", development: "개발 환경", testing: "테스트 환경", production: "프로덕션 환경" },
  es: { system: "Sistema", systemHosts: "Hosts del sistema", systemHint: "/etc/hosts actual · Solo lectura", shared: "Compartido", sharedName: "Configuración compartida", sharedHint: "Siempre incluida", environments: "Entornos", add: "Añadir", activate: "Activar", active: "Activo", delete: "Eliminar", empty: "Añade una asignación por línea", development: "Desarrollo", testing: "Pruebas", production: "Producción" },
  fr: { system: "Système", systemHosts: "Hosts système", systemHint: "/etc/hosts actuel · Lecture seule", shared: "Partagé", sharedName: "Configuration partagée", sharedHint: "Toujours incluse", environments: "Environnements", add: "Ajouter", activate: "Activer", active: "Actif", delete: "Supprimer", empty: "Ajoutez une correspondance par ligne", development: "Développement", testing: "Test", production: "Production" },
  de: { system: "System", systemHosts: "System-Hosts", systemHint: "Aktuelle /etc/hosts · Schreibgeschützt", shared: "Gemeinsam", sharedName: "Gemeinsame Konfiguration", sharedHint: "Immer enthalten", environments: "Umgebungen", add: "Hinzufügen", activate: "Aktivieren", active: "Aktiv", delete: "Löschen", empty: "Eine Zuordnung pro Zeile hinzufügen", development: "Entwicklung", testing: "Test", production: "Produktion" },
  "pt-BR": { system: "Sistema", systemHosts: "Hosts do sistema", systemHint: "/etc/hosts atual · Somente leitura", shared: "Compartilhado", sharedName: "Configuração compartilhada", sharedHint: "Sempre incluída", environments: "Ambientes", add: "Adicionar", activate: "Ativar", active: "Ativo", delete: "Excluir", empty: "Adicione um mapeamento por linha", development: "Desenvolvimento", testing: "Teste", production: "Produção" },
  ru: { system: "Система", systemHosts: "Системный Hosts", systemHint: "Текущий /etc/hosts · Только чтение", shared: "Общее", sharedName: "Общая конфигурация", sharedHint: "Всегда включена", environments: "Окружения", add: "Добавить", activate: "Активировать", active: "Активно", delete: "Удалить", empty: "Добавьте одно сопоставление на строку", development: "Разработка", testing: "Тестирование", production: "Продакшен" },
};
